//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAPRO.Entidadengres
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Egreso_Manual_los_negritos
    {
        public int Id_egreso { get; set; }
        public string Digital { get; set; }
        public string Fecha_ingreso { get; set; }
        public string Numero_factura { get; set; }
        public string Cedula_Juridica { get; set; }
        public string Existe_fisica { get; set; }
        public string GTI { get; set; }
        public string Nombre_comercio { get; set; }
        public string Id_detalle { get; set; }
        public string Id_partida { get; set; }
        public string Monto_factura { get; set; }
        public string Estado_pago { get; set; }
        public string Plazo_pago { get; set; }
        public byte[] Pdf_factura { get; set; }
        public string Nombre_pdf { get; set; }
        public string Id_Centro_costos { get; set; }
        public string Id_metodo_pago { get; set; }
        public string Id_banco { get; set; }
        public string Moneda { get; set; }
        public string Tipo_cambio { get; set; }
        public string Mes { get; set; }
        public string TotalIva { get; set; }
        public string Estado { get; set; }
    }
}
