//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAPRO.EntipagoEmple
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pago_emple_los_negritos
    {
        public int Id_comprobante { get; set; }
        public string Mes { get; set; }
        public string Periodo { get; set; }
        public Nullable<int> Quincena { get; set; }
        public string Moneda { get; set; }
        public string Fecha_registro { get; set; }
        public string Id_colaborador { get; set; }
        public string Salario_quincenal { get; set; }
        public string Comision { get; set; }
        public string Prestamos { get; set; }
        public string Dias_sinGoce { get; set; }
        public string Total_sinGoce { get; set; }
        public string Dias_feriados { get; set; }
        public string Total_feriados { get; set; }
        public string Horas_extras { get; set; }
        public string Total_extras { get; set; }
        public string Salario_neto { get; set; }
        public string Porcen_caja { get; set; }
        public string Impuesto_renta { get; set; }
        public string Otras_deducc { get; set; }
        public string Detalle_otras_deduc { get; set; }
        public string Total_deduc { get; set; }
        public string Saldo_anterior { get; set; }
        public string Saldo { get; set; }
        public string Total_depositado { get; set; }
        public string Id_banco { get; set; }
        public string Estado { get; set; }
        public string Id_centro_costos { get; set; }
        public byte[] Pdf_compro { get; set; }
        public string Total_caja { get; set; }
        public string Realname_pdf { get; set; }
    }
}
